### GET all items
GET http://localhost:8080/api/items

### GET item by id
GET http://localhost:8080/api/items/667067300aa8f19caa0e3763

### POST
POST http://localhost:8080/api/items
Content-Type: application/json

{
    "name": "eminem",
    "description": "thingy description",
    "price": 1
}
